=== tc-ca/ROM.QM/src/schema/template.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "Comment": {
            "additionalProperties": false,
            "properties": {
                "option": {
                    "$ref": "#/definitions/Option"
                },
                "value": {
                    "type": "string"
                }
            },
            "required": [
                "option",
                "value"
            ],
            "type": "object"
        },
        "ComparisonOperator": {
            "enum": [
                "equal",
                "greaterThen",
                "lengthGreaterThen",
                "lengthLessThen",
                "lessThen",
                "notEqual"
            ],
            "type": "string"
        },
        "DependencyGroup": {
            "additionalProperties": false,
            "properties": {
                "childValidatorName": {
                    "type": "null"
                },
                "questionDependencies": {
                    "items": {
                        "$ref": "#/definitions/QuestionDependency"
                    },
                    "type": "array"
                },
                "ruleType": {
                    "$ref": "#/definitions/DependencyGroupType"
                }
            },
            "required": [
                "childValidatorName",
                "questionDependencies",
                "ruleType"
            ],
            "type": "object"
        },
        "DependencyGroupType": {
            "enum": [
                "validation",
                "validationValue",
                "visibility"
            ],
            "type": "string"
        },
        "Dependent": {
            "additionalProperties": false,
            "properties": {
                "guid": {
                    "type": "string"
                }
            },
            "required": [
                "guid"
            ],
            "type": "object"
        },
        "Group": {
            "additionalProperties": false,
            "properties": {
                "domSuffix": {
                    "type": "string"
                },
                "expansionPanels": {
                    "items": {
                        "type": "number"
                    },
                    "type": "array"
                },
                "htmlElementId": {
                    "type": "string"
                },
                "isRepeatable": {
                    "type": "boolean"
                },
                "isVisible": {
                    "type": "boolean"
                },
                "order": {
                    "type": "number"
                },
                "primaryKey": {
                    "type": "string"
                },
                "questions": {
                    "items": {
                        "$ref": "#/definitions/Question"
                    },
                    "type": "array"
                },
                "title": {
                    "$ref": "#/definitions/Title"
                }
            },
            "required": [
                "domSuffix",
                "expansionPanels",
                "htmlElementId",
                "isRepeatable",
                "isVisible",
                "order",
                "primaryKey",
                "questions",
                "title"
            ],
            "type": "object"
        },
        "Option": {
            "enum": [
                "n/a",
                "optional",
                "required"
            ],
            "type": "string"
        },
        "Picture": {
            "additionalProperties": false,
            "properties": {
                "option": {
                    "$ref": "#/definitions/Option"
                },
                "value": {
                    "items": {
                        "$ref": "#/definitions/PictureItems"
                    },
                    "type": "array"
                }
            },
            "required": [
                "option",
                "value"
            ],
            "type": "object"
        },
        "PictureItems": {
            "additionalProperties": false,
            "properties": {
                "base64Value": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            },
            "required": [
                "base64Value",
                "description",
                "title"
            ],
            "type": "object"
        },
        "Question": {
            "additionalProperties": false,
            "properties": {
                "childQuestions": {
                    "items": {
                        "$ref": "#/definitions/Question"
                    },
                    "type": "array"
                },
                "dependants": {
                    "default": [
                    ],
                    "items": {
                        "$ref": "#/definitions/Dependent"
                    },
                    "type": "array"
                },
                "dependencyGroups": {
                    "items": {
                        "$ref": "#/definitions/DependencyGroup"
                    },
                    "type": "array"
                },
                "guid": {
                    "type": "string"
                },
                "id": {
                    "type": "number"
                },
                "isMultiple": {
                    "type": "boolean"
                },
                "isRepeatable": {
                    "type": "boolean"
                },
                "isRepeated": {
                    "type": "boolean"
                },
                "isSamplingAllowed": {
                    "type": "boolean"
                },
                "isVisible": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "response": {
                    "type": "null"
                },
                "responseOptions": {
                    "anyOf": [
                        {
                            "items": {
                                "$ref": "#/definitions/QuestionResponseOption"
                            },
                            "type": "array"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "samplingRecord": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/SamplingRecord"
                        },
                        {
                            "type": "null"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "sortOrder": {
                    "type": "number"
                },
                "text": {
                    "$ref": "#/definitions/Title"
                },
                "type": {
                    "$ref": "#/definitions/QuestionResponseType"
                },
                "validationRules": {
                    "items": {
                        "$ref": "#/definitions/ValidationRule"
                    },
                    "type": "array"
                },
                "violationInfo": {
                    "$ref": "#/definitions/ViolationInfo"
                }
            },
            "required": [
                "childQuestions",
                "dependants",
                "dependencyGroups",
                "guid",
                "id",
                "isMultiple",
                "isVisible",
                "name",
                "response",
                "responseOptions",
                "sortOrder",
                "text",
                "type",
                "validationRules",
                "violationInfo"
            ],
            "type": "object"
        },
        "QuestionDependency": {
            "additionalProperties": false,
            "properties": {
                "dependsOnQuestion": {
                    "$ref": "#/definitions/QuestionDependencyItem"
                },
                "validationAction": {
                    "anyOf": [
                        {
                            "enum": [
                                "equal",
                                "greaterThen",
                                "lengthGreaterThen",
                                "lengthLessThen",
                                "lessThen",
                                "notEqual"
                            ],
                            "type": "string"
                        },
                        {
                            "type": "null"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "validationValue": {
                    "type": "string"
                }
            },
            "required": [
                "dependsOnQuestion",
                "validationAction",
                "validationValue"
            ],
            "type": "object"
        },
        "QuestionDependencyItem": {
            "additionalProperties": false,
            "properties": {
                "guid": {
                    "type": "string"
                }
            },
            "required": [
                "guid"
            ],
            "type": "object"
        },
        "QuestionResponseOption": {
            "additionalProperties": false,
            "properties": {
                "externalComment": {
                    "$ref": "#/definitions/Comment"
                },
                "id": {
                    "type": "number"
                },
                "internalComment": {
                    "$ref": "#/definitions/Comment"
                },
                "isProvisionCollapsed": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "picture": {
                    "$ref": "#/definitions/Picture"
                },
                "provisions": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "searchProvisions": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "selectedProvisions": {
                    "items": {
                    },
                    "type": "array"
                },
                "selectedProvisionsTitles": {
                    "items": {
                    },
                    "type": "array"
                },
                "sortOrder": {
                    "type": "number"
                },
                "text": {
                    "$ref": "#/definitions/Title"
                },
                "value": {
                    "type": "string"
                }
            },
            "required": [
                "externalComment",
                "id",
                "internalComment",
                "isProvisionCollapsed",
                "name",
                "picture",
                "provisions",
                "searchProvisions",
                "selectedProvisions",
                "sortOrder",
                "text",
                "value"
            ],
            "type": "object"
        },
        "QuestionResponseType": {
            "enum": [
                "image",
                "number",
                "radio",
                "reference",
                "select",
                "text"
            ],
            "type": "string"
        },
        "SamplingRecord": {
            "additionalProperties": false,
            "properties": {
                "approximateTotal": {
                    "type": "string"
                },
                "nonCompliances": {
                    "type": "string"
                },
                "sampleSize": {
                    "type": "string"
                }
            },
            "required": [
                "approximateTotal",
                "nonCompliances",
                "sampleSize"
            ],
            "type": "object"
        },
        "SearchableProvision": {
            "additionalProperties": false,
            "properties": {
                "leg": {
                    "type": "string"
                },
                "questions": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                }
            },
            "required": [
                "leg",
                "questions"
            ],
            "type": "object"
        },
        "Title": {
            "additionalProperties": false,
            "properties": {
                "en": {
                    "type": "string"
                },
                "fr": {
                    "type": "string"
                }
            },
            "required": [
                "en",
                "fr"
            ],
            "type": "object"
        },
        "ValidationRule": {
            "additionalProperties": false,
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "errorMessage": {
                    "$ref": "#/definitions/Title"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/ValidationRuleType"
                },
                "value": {
                    "type": [
                        "null",
                        "string",
                        "number"
                    ]
                }
            },
            "required": [
                "enabled",
                "errorMessage",
                "name",
                "type",
                "value"
            ],
            "type": "object"
        },
        "ValidationRuleType": {
            "enum": [
                "max",
                "maxLength",
                "min",
                "minLength",
                "require"
            ],
            "type": "string"
        },
        "ViolationInfo": {
            "additionalProperties": false,
            "properties": {
                "matchingType": {
                    "$ref": "#/definitions/ComparisonOperator"
                },
                "responseToMatch": {
                    "type": "string"
                }
            },
            "required": [
                "matchingType",
                "responseToMatch"
            ],
            "type": "object"
        }
    },
    "properties": {
        "groups": {
            "items": {
                "$ref": "#/definitions/Group"
            },
            "type": "array"
        },
        "name": {
            "description": "name of the template",
            "type": "string"
        },
        "readOnly": {
            "type": "boolean"
        },
        "searchableProvisions": {
            "anyOf": [
                {
                    "items": {
                        "$ref": "#/definitions/SearchableProvision"
                    },
                    "type": "array"
                },
                {
                    "type": "null"
                }
            ]
        },
        "templateid": {
            "description": "unique id (GUID) of the template",
            "type": "string"
        },
        "title": {
            "$ref": "#/definitions/Title"
        }
    },
    "required": [
        "groups",
        "name",
        "readOnly",
        "searchableProvisions",
        "templateid",
        "title"
    ],
    "type": "object"
}

=== tc-ca/ROM.QM/public/static/templates/ItermediateBulk.json
{
    "title": {
        "en": "INTERMEDIATEBULK",
        "fr": "INTERMEDIATEBULK"
    },
    "name": "INTERMEDIATE BULK CONTAINERS DESIGN AND MANUFACTURE FOR THE TRANSPORTATION OF DANGEROUS GOODS PURSUANT TO PART 1 OF CGSB-43.146-2002",
    "groups": [
        {
            "title": {
                "en": "COMPANY DETAILS",
                "fr": "DÉTAILS DE LA COMPAGNIE"
            },
            "primaryKey": "GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
            "isRepeatable": false,
            "isVisible": true,
            "order": 0,
            "questions": [
                {
                    "name": "QTN_TYPFNSPCTN_SLCT_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                    "id": 1,
                    "guid": "2a52bb18-ff63-42e6-be03-84afe116deb7",
                    "sortOrder": 1,
                    "isVisible": true,
                    "isMultiple": true,
                    "text": {
                        "en": "Type of Inspection",
                        "fr": "Type d'inspection"
                    },
                    "type": "select",
                    "response": null,
                    "isSamplingAllowed": false,
                    "samplingRecord": null,
                    "isRepeatable": false,
                    "isRepeated": false,
                    "responseOptions": [
                        {
                            "id": 1,
                            "name": "RSPNS_NTL_QTN_TYPFNSPCTN_SLCT_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                            "sortOrder": 1,
                            "text": {
                                "en": "Initial",
                                "fr": "nitiale"
                            },
                            "value": "true",
                            "internalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "externalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "picture": {
                                "option": "optional",
                                "value": []
                            },
                            "provisions": [],
                            "selectedProvisions": [],
                            "searchProvisions": null,
                            "isProvisionCollapsed": false
                        },
                        {
                            "id": 2,
                            "name": "RSPNS_VRFCTN_QTN_TYPFNSPCTN_SLCT_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                            "sortOrder": 2,
                            "text": {
                                "en": "Verification",
                                "fr": "Vérification"
                            },
                            "value": "False",
                            "internalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "externalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "picture": {
                                "option": "optional",
                                "value": []
                            },
                            "provisions": [],
                            "selectedProvisions": [],
                            "selectedProvisionsTitles": [],
                            "searchProvisions": null,
                            "isProvisionCollapsed": false
                        }
                    ],
                    "validationRules": [
                        {
                            "name": "require",
                            "enabled": true,
                            "type": "require",
                            "value": null,
                            "errorMessage": {
                                "en": "Required",
                                "fr": "FR: Required"
                            }
                        }
                    ],
                    "violationInfo": {
                        "responseToMatch": "false",
                        "matchingType": "equal"
                    },
                    "childQuestions": [],
                    "dependants": [
                        {
                            "guid": "91ad851b-18b9-421f-a5a8-e3ba1b5dc57a"
                        },
                        {
                            "guid": "379230fa-1830-4ef5-9f00-a9e68c60efc0"
                        }
                    ],
                    "dependencyGroups": []
                },
                {
                    "name": "QTN_FNTLNSPCTN,PHYS_RD_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                    "id": 3,
                    "guid": "91ad851b-18b9-421f-a5a8-e3ba1b5dc57a",
                    "sortOrder": 2,
                    "isVisible": false,
                    "isMultiple": true,
                    "text": {
                        "en": "If initial inspection, physical address matches address on application for registration?",
                        "fr": "S'il s'agit d'une inspection initiale, l'adresse physique correspond à la demande d'inscription? If"
                    },
                    "type": "radio",
                    "response": null,
                    "isSamplingAllowed": false,
                    "samplingRecord": null,
                    "isRepeatable": false,
                    "isRepeated": false,
                    "responseOptions": [
                        {
                            "id": 1,
                            "name": "RSPNS_YS_QTN_FNTLNSPCTN,PHYS_RD_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                            "sortOrder": 1,
                            "text": {
                                "en": "Yes",
                                "fr": "FR: Yes"
                            },
                            "value": "true",
                            "internalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "externalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "picture": {
                                "option": "optional",
                                "value": []
                            },
                            "provisions": [],
                            "selectedProvisions": [],
                            "searchProvisions": null,
                            "isProvisionCollapsed": false
                        },
                        {
                            "id": 2,
                            "name": "RSPNS_N_QTN_FNTLNSPCTN,PHYS_RD_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                            "sortOrder": 2,
                            "text": {
                                "en": "No",
                                "fr": "FR: No"
                            },
                            "value": "false",
                            "internalComment": {
                                "option": "optional",
                                "value": ""
                            },
                            "externalComment": {
                                "option": "required",
                                "value": ""
                            },
                            "picture": {
                                "option": "optional",
                                "value": []
                            },
                            "provisions": [],
                            "selectedProvisions": [],
                            "selectedProvisionsTitles": [],
                            "searchProvisions": null,
                            "isProvisionCollapsed": false
                        }
                    ],
                    "validationRules": [
                        {
                            "name": "require",
                            "enabled": true,
                            "type": "require",
                            "value": null,
                            "errorMessage": {
                                "en": "Required",
                                "fr": "FR: Required"
                            }
                        }
                    ],
                    "violationInfo": {
                        "responseToMatch": "false",
                        "matchingType": "equal"
                    },
                    "childQuestions": [],
                    "dependants": [],
                    "dependencyGroups": [
                        {
                            "ruleType": "visibility",
                            "childValidatorName": null,
                            "questionDependencies": [
                                {
                                    "dependsOnQuestion": {
                                        "guid": "2a52bb18-ff63-42e6-be03-84afe116deb7"
                                    },
                                    "validationAction": "equal",
                                    "validationValue": "true"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "QTN_FVRFCTNNSPCTN,P_RD_GRP_CMPNYDTLS_TMPLT_QSTNNRTTLN",
                    "id": 4,
                    "guid": "379230fa-1830-4ef5-9f00-a9e68c60efc0",
                    "sortOrder": 2,
                    "isVisible": false,
                    "isMultiple": true,
                    "text": {
